### ISSUE TITLE
Double free or corruption error

### ISSUE THREAD

**Issue by nootanghimire** [N3Ur0t0x1c/Sha1#2]
I am guessing that you have free'd the same memory more than two times?

**Comment by ghost** [comment]
are u saying this for the latest push..

**Comment by nootanghimire** [comment]
Yes sir. I was able to reproduce this error on Ubuntu 13.10 in gcc
![error](https://f.cloud.github.com/assets/2210043/2032905/6f5804e2-8915-11e3-9e8d-b47e89392c28.png)

**Comment by ghost** [comment]
but working fine on my system.

**Comment by nootanghimire** [comment]
Still getting Segfaults now and then, but since SHA1 Hashes seem to be ok, Closing this one!
