### ISSUE TITLE
Does not work properly!

### ISSUE THREAD

**Issue by musaa32** [N3Ur0t0x1c/Sha1#5]
i have tested it on Windows 10/64Bit (I7) and on Ubuntu 14.04 with the gcc compiler. 
It works on my MacOS and on Windows 10/64Bit(Intel Core M). 
e.g "Hallo Welt!" Hash should be "726C3E88 61AB0652 A5043EA5 FAFF6D3E F33FB209"
but on Ubuntu and some Windows machines I got:  "711EE681 936F579C 2DEF3D41 6697A5FE 548DB753"

**Comment by nootanghimire** [comment]
I'm guessing it's the issue with how did you supply the string. Can you post the command you executed and the output in the comment below?

**Comment by nootanghimire** [comment]
Or maybe the issue lies within the header file "strings.h". Given that it's some BSD-crap which MacOS is based on, it might cause those issues. I'd consider both this and previous comment. :)

**Comment by musaa32** [comment]
sure 

```
   int main(int argc, const char * argv[]) {
    
    // Variablen initialisieren
    FILE *dateiZeiger;
    long int dateiLaenge;
    unsigned char *buffer;
    struct sha *shaSt;
    int fehler;
    int i;
    
    // Speicher reservieren
    shaSt = (struct sha *) malloc(sizeof(struct sha));
    // Anzahl der Argumente Prüfen
    if(argc == 0 || argc > 2)
    {
        printf("Datei angeben!\n");
        exit(0);
    }
    
    /* DEBUG */
    /*
    for (int i = 0; i < argc; ++i)
    {
        printf("argv[%d]: %s\n", i, argv[i]);
    }
    */
    
    // Datei öffnen
    if((dateiZeiger =fopen(argv[1],"rb")) == NULL)
    {
        printf("Datei konnte nicht gefunden werden!\n");
        exit(0);
    }
    
    // Dateilänge ermitteln
    fseek(dateiZeiger, 0, SEEK_END);
    dateiLaenge = ftell(dateiZeiger);
    fseek(dateiZeiger, 0, SEEK_SET);

    
    
    //Speicher reservieren
    buffer = (unsigned char *) malloc(dateiLaenge);
    
    if(!buffer)
    {
        printf("Fehler(Buffer)!\n");
        exit(0);
    }
    
    // Gesamte Datei lesen
    fread(buffer, dateiLaenge, 1, dateiZeiger);
    fclose(dateiZeiger);
    
    // calculate_sha1
    fehler = sha1_berechnen(shaSt, buffer, dateiLaenge);
    
    if(fehler != 0)
    {
        printf("Fehler beim Berechnen des Hashwertes\n");
        exit (0);
    }
    
    
    //print hash
    printf("\n\nSHA1 Hash:\n");
    for(i=0; i<5; i++)
    {
        printf("%X ",shaSt->hash[i]);
    }
    printf("\n");
    free(buffer);
    free(shaSt);
    
     printf("\n\nHallo Welt!:\n726C3E88 61AB0652 A5043EA5 FAFF6D3E F33FB209\n\n");
    
    
    
    return 0;
}
```

**Comment by nootanghimire** [comment]
@musaa32  : I meant the "command" you executed and the "output" of the command! Not the translated code. (which is hard for me to understand) .

I just executed this in my debian and it worked fine, so.

**Comment by musaa32** [comment]
I have splitted the files into sha.c and sha.h.

`gcc -oc test sha.c sha.h main.c`

```
sha.c: In function ‘ sha1_berechnen’:
sha.c:56:32: warning: incompatible implicit declaration of built-in function ‘malloc’ [enabled by default]
     buffer = (unsigned char *) malloc((bits/8)+8);
                                ^
sha.c:64:5: warning: incompatible implicit declaration of built-in function ‘memcpy’ [enabled by default]
     memcpy(buffer, text, laenge);
     ^
```

executed with
`./test test.txt`

input file test.txt
`Hallo Welt!`

result on ubuntu:

> SHA1 Hash:
> 711EE681 936F579C 2DEF3D41 6697A5FE 548DB753 
> 
> Hallo Welt!:
> 726C3E88 61AB0652 A5043EA5 FAFF6D3E F33FB209

I think the problem is memcpy(..)

**Comment by nootanghimire** [comment]
My guess is that there is some issue with file reading. I can reproduce the error but with different hash every time. Try strlen()-ing the string you get and see if the length matches? Those warnings should go if you replace "strings.h" with "string.h"

**Comment by musaa32** [comment]
strlen says 15 for "Hallo Welt!" so its false, but ftell says 12

**Comment by nootanghimire** [comment]
Maybe Issues with Newline? EOFs?

**Comment by musaa32** [comment]
thank you for your support
